# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt
#
# ReadTheDocs configuration.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  builder: html
  configuration: doc/conf.py

# Build all the formats
formats:
  - epub
  - htmlzip
  - pdf

python:
  # PYVERSIONS: the version we use for building docs. Check tox.ini[doc] also.
  version: 3.8
  install:
    - requirements: doc/requirements.pip
    - method: pip
      path: .
  system_packages: false
